name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - uses: "actions/checkout@v3"
      - name: Setup Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          pip install -r requirements_dev.txt
      - name: Run pytest
        run: |
          pytest --cov=custom_components/wewash
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
